#! /bin/sh

# Initialize keys
sxhkd &

# Compositor
compton --config $HOME/.config/compton/compton.conf -b

# Set volume to a reasonable level#
amixer set Master 55% &

# Toggle Numlock on#
numlockx &

# Beautify the OS#
. "${HOME}/.cache/wal/colors.sh" &
#feh --bg-scale $wallpaper

# Start polybar#
sh ~/.config/polybar/bspwm.sh &

# Wallpaper (Managed by feh/wal)
nitrogen --restore &

# Better cursor
xsetroot -cursor_name left_ptr &

## bspwm settings

bspc monitor DVI-D-0 -d I II III
bspc monitor DP-0 -d IV V VI
bspc monitor HDMI-0 -d VII VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# Set the border colors from wal vars set earlier
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Modify pointer functionality
bspc config pointer_modifier super
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

# BSPC rules for applications
bspc rule -a steam desktop='^4' stated=tiled follow=off
bspc rule -a Gimp desktop='^5' state=fullscreen follow=on
bspc rule -a Chromium desktop='^7' state=tiled follow=off
bspc rule -a Firefox desktop='^1' state=tiled follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a SkyrimSE.exe state=floating

# Fix for Java programs. Make sure wmname is installed
bspc config wm_name LG3D
wmname LG3D
